#!/usr/bin/env bash

set -eo pipefail

export PATH="../kagome/node_modules/.bin:$PATH"

set -x
tsc

cp index.css ../dram.cf/kagome/index.css
cp ../kagome/dist/kagome.min.js ../dram.cf/kagome/vendor/kagome.js
cp dist/demo.js ../dram.cf/kagome/dist/demo.js

